"""Removed Label table

Revision ID: 112d1590197d
Revises: 349d217f69dc
Create Date: 2024-05-03 16:06:24.323835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112d1590197d'
down_revision = '349d217f69dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
