"""add fk in reply_note

Revision ID: 330bd794a257
Revises: 171c252b4ffe
Create Date: 2024-05-02 23:01:56.318136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330bd794a257'
down_revision = '171c252b4ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send__note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labels_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('anonymous', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_labels_id', 'labels', ['labels_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send__note', schema=None) as batch_op:
        batch_op.drop_constraint('fk_labels_id', type_='foreignkey')
        batch_op.drop_column('anonymous')
        batch_op.drop_column('labels_id')

    # ### end Alembic commands ###
