"""change table name

Revision ID: d0422b253681
Revises: 330bd794a257
Create Date: 2024-05-02 23:05:01.714374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0422b253681'
down_revision = '330bd794a257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('send',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('labelsId', sa.Integer(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['labelsId'], ['labels.id'], name='fk_labelsId'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='fk_userId'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('send', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_send_timestamp'), ['timestamp'], unique=False)

    op.create_table('reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('sendId', sa.Integer(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sendId'], ['send.id'], name='fk_sendId'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='fk_userId'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reply_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('send__note', schema=None) as batch_op:
        batch_op.drop_index('ix_send__note_timestamp')

    op.drop_table('send__note')
    with op.batch_alter_table('reply__note', schema=None) as batch_op:
        batch_op.drop_index('ix_reply__note_timestamp')

    op.drop_table('reply__note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply__note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('anonymous', sa.BOOLEAN(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reply__note', schema=None) as batch_op:
        batch_op.create_index('ix_reply__note_timestamp', ['timestamp'], unique=False)

    op.create_table('send__note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('labels_id', sa.INTEGER(), nullable=True),
    sa.Column('anonymous', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['labels_id'], ['labels.id'], name='fk_labels_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('send__note', schema=None) as batch_op:
        batch_op.create_index('ix_send__note_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reply_timestamp'))

    op.drop_table('reply')
    with op.batch_alter_table('send', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_send_timestamp'))

    op.drop_table('send')
    # ### end Alembic commands ###
