"""remove timestamp

Revision ID: e22dfa71b59c
Revises: d0422b253681
Create Date: 2024-05-02 23:07:06.551877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22dfa71b59c'
down_revision = 'd0422b253681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_index('ix_reply_timestamp')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('send', schema=None) as batch_op:
        batch_op.drop_index('ix_send_timestamp')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_send_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_reply_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
